### ISSUE TITLE
Declare supported Node version

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/rhd-frontend#108]
Can we decide on a version of Node to support and document that with an .nvmrc file in the root of this repo? This would be useful for build processes.

- [ ] The supported Node version is documented in an .nvmrc file in the root of the rhd-frontend repo

**Comment by robpblake** [comment]
@jordanpagewhite @KamiQuasi Please consider that we should support SCL versions of node here. Currently we run [rh-nodejs8](https://www.softwarecollections.org/en/scls/rhscl/rh-nodejs8/) SCL. All of the SCL supported versions of Node are listed [here](https://www.softwarecollections.org/en/scls/?search=nodejs).

**Comment by jordanpagewhite** [comment]
Thanks Rob. That is a good point. I am happy with any supported version of Node. I just want to make sure all of us humans, and probably more importantly our build scripts, are using the same version of Node to build this dependency.
