### ISSUE TITLE
Update NPM scripts to allow Drupal server to generate CSS files

### ISSUE THREAD

**Issue by KamiQuasi** [redhat-developer/rhd-frontend#111]

**Comment by jordanpagewhite** [comment]
@robpblake We briefly discussed this in Slack at the very end of last week, but would you be satisfied with the idea of using our build processes to executing a couple of `npm` commands that would build out the dist files for the `rhd-frontend` dependency? From the perspective of Drupal, we just need some assets (CSS and JS files) that we can reference in the theme, specifically as librar(ies) in the `.libraries.yml` file and possibly the `.info.yml` file depending on how we want to attach these specific librar(ies) to requests.

**Comment by jordanpagewhite** [comment]
We will also have to remove `src` from the `.npmignore` file if we want to include the `redhat-developer/rhd-frontend` repo as a dependency of our Drupal theme (via `npm`) and have build processes be responsible for building the assets.

**Comment by robpblake** [comment]
@jordanpagewhite Yeah sounds fine to me as that's basically what we do now.

**Comment by jordanpagewhite** [comment]
Cool, thanks Rob
