### ISSUE TITLE
Refine PF breakpoints values

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/rhd-frontend#126]
↓↓↓↓ Content will remain the same for screens<320px and margins will continue to expand
--breakpoint--xs: 320
margins: 16
--breakpoint--sm: 480
margins: 16
--breakpoint--md: 768
margins: 32
--breakpoint--lg: 1024
margins: 32
--breakpoint--xl: 1440
margins: 64
↑↑↑↑ Content will remain the same for screens>1440px and margins will continue to expand
(will not be using pf-global--breakpoint--2xl)

**Comment by mindreeper2420** [comment]
closing as this was marked as done
