### ISSUE TITLE
Product Try-It Hero

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/rhd-frontend#155]
- [x] Text
- [x] Image
- [x] CTA
- [x] Link

This can heavily borrow from the design(s) for the Product Download Hero here: https://marvelapp.com/c6c454h/screen/60231484

Ask SJ or Gina if further UX direction is needed.

Example screenshots (current state of component):

<img width="1643" alt="Screen Shot 2019-09-11 at 8 21 04 AM" src="https://user-images.githubusercontent.com/7155034/64710790-6e62c000-d46d-11e9-9178-8ee2b99d9f25.png">

Dark visual style,
No image set,
Learn More link set

<img width="1645" alt="Screen Shot 2019-09-11 at 8 21 59 AM" src="https://user-images.githubusercontent.com/7155034/64710793-6e62c000-d46d-11e9-93de-9287f8fc1777.png">

Dark visual style,
No image set,
Learn More link set

<img width="1651" alt="Screen Shot 2019-09-11 at 8 22 37 AM" src="https://user-images.githubusercontent.com/7155034/64710794-6e62c000-d46d-11e9-9b72-c27e6f1e3e45.png">

Light visual style,
No 'Learn More' link set,
Image set

**Comment by mindreeper2420** [comment]
@jordanpagewhite is there a screenshot or page that shows this component as used today? I haven't found anything yet.

**Comment by jordanpagewhite** [comment]
@mindreeper2420 I just added 3 example screenshots to demonstrate the status of the component today. Let me know if you feel any other details could be helpful.

**Comment by mindreeper2420** [comment]
@jordanpagewhite awesome, thank you. Those should be plenty to get a good, flexible component in place.
