### ISSUE TITLE
Video Card

### ISSUE THREAD

**Issue by KamiQuasi** [redhat-developer/rhd-frontend#157]
See designs in Marvel: https://marvelapp.com/c6c454h/screen/60099025

The Video card should be identical to our existing Card implementation, but it has a play icon positioned over the hero image and a timestamp positioned over the bottom right corner of the hero image.

**Comment by mindreeper2420** [comment]
@jordanpagewhite A demo of this was implemented, but I do not know how usable it is in Drupal: https://redhat-developer.github.io/rhd-frontend/components/card-html/. There is a section towards to bottom labelled "Videos"
