### ISSUE TITLE
Events Hero

### ISSUE THREAD

**Issue by KamiQuasi** [redhat-developer/rhd-frontend#169]
Visual Styles Needed:
- [x] Default (not a visual style)
- [x] Light
- [x] Slim

**Comment by gdoyle1** [comment]
@mindreeper2420 I believe we removed "slim" from visual style options. See screen 3 here: https://marvelapp.com/c6c454h. This is the mock for the default style (which is always on that dark background as seen here (https://developers.redhat.com/devnationlive-london/). If you need a spec for the light visual style, please let me know! We have a standard background image that is applied to that now.

**Comment by mindreeper2420** [comment]
@gdoyle1 If you could provide a light visual style, that'd be great. That way, we'd at least have it covered if needed. Thanks!

**Comment by gdoyle1** [comment]
@mindreeper2420 you can reference the specs here on screen 8! https://marvelapp.com/c6c454h

**Comment by mindreeper2420** [comment]
Layout cleaned up as part of PR https://github.com/redhat-developer/rhd-frontend/pull/276
