### ISSUE TITLE
Curated Content

### ISSUE THREAD

**Issue by KamiQuasi** [redhat-developer/rhd-frontend#175]
- [x] Cards

#### Example screenshot(s)

<img width="1071" alt="Screen Shot 2019-09-12 at 9 10 38 AM" src="https://user-images.githubusercontent.com/7155034/64801403-4c387300-d53d-11e9-9195-0809eef27028.png">

**Comment by mindreeper2420** [comment]
There is a basic version of the Curated Content at the bottom of the Katacoda reference page, utilizing an existing Card styles.

https://redhat-developer.github.io/rhd-frontend/pages/katacoda/
