### ISSUE TITLE
Support legacy button styles

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/rhd-frontend#199]
Old button styles such as `button heavy-cta red` no longer work. We need some way to support these legacy button styles with our new button styles. There are a lot of buttons implemented in WYSIWYG content.

Legacy button styles
"button heavy-cta"
"button heavy-cta red"
"button heavy-cta vlue"
"button medium-cta"
"button medium-cta red"
"button medium-cta blue"

**Comment by mindreeper2420** [comment]
@jordanpagewhite is there a file that can be referenced to get the legacy class names?
