### ISSUE TITLE
Fix author element padding

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/rhd-frontend#225]
The author element lost its padding in the video hero now. This is what it looks like now:
<img width="228" alt="Screen Shot 2019-09-19 at 10 54 32 AM" src="https://user-images.githubusercontent.com/30870144/65255570-21fe2c80-dacc-11e9-9e6e-163444dbb2dd.png">

Should follow the spec here (8px spacing between author image and text) : https://marvelapp.com/c6c454h screen 3. 

cc: @rogeralloymagnetic @mindreeper2420

**Comment by mindreeper2420** [comment]
@gdoyle1 This is what I'm seeing on the demo site now...it seems the padding is actually there?
![image](https://user-images.githubusercontent.com/4032718/65256045-eadc4b00-dacc-11e9-9231-f2e34ef25615.png)

**Comment by mindreeper2420** [comment]
Oof - this is a Chrome vs Firefox issue. On Firefox the `grid-gap` property works and provides the spacing. On Chrome, it is not fully supported in the way it was implemented, so the spacing is missing. I'll update to use a margin, rather than gaps between the grid elements.

**Comment by gdoyle1** [comment]
@mindreeper2420 Ah interesting, okay thanks for doing so!
