### ISSUE TITLE
Fix display of multiple CTAs in Card Grid

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/rhd-frontend#238]
How should we display multiple CTAs in a Card Grid-based component (assembly type)?

### Current screenshot

<img width="884" alt="Screen Shot 2019-09-23 at 9 49 33 AM" src="https://user-images.githubusercontent.com/7155034/65445752-c394bf00-dde7-11e9-88d1-bb5854cf6044.png">

**Comment by sjcox-rh** [comment]
@jordanpagewhite they should be displayed side by side with 24px space in between them and 32ox from bottom of card to buttons.

Here is a mock:
<img width="1067" alt="Screen Shot 2019-09-24 at 2 52 31 PM" src="https://user-images.githubusercontent.com/16257540/65553150-0be0d980-dedb-11e9-9226-c0f8f84c709e.png">

**Comment by jordanpagewhite** [comment]
Thanks @sjcox-rh

**Comment by jordanpagewhite** [comment]
This was closed by #279
