### ISSUE TITLE
Video Hero: Visual Styles Missing

### ISSUE THREAD

**Issue by adelasofia** [redhat-developer/rhd-frontend#252]
Visual Styles missing:
- Slim
- Full Width Video

**Comment by mindreeper2420** [comment]
@sjcox-rh @gdoyle1 I'm not seeing a Slim or Full Width Video Hero in the Marvel project (https://marvelapp.com/c6c454h/screen/61796034), just the Default, Multiple Authors, and mobile versions. Are there supposed to be Slim and Full Width version created, or are those being dropped?
