### ISSUE TITLE
Add border to cards

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/rhd-frontend#282]
Need to replace the box shadow on cards with 2 pixel border color #EDEDED

**Comment by alistairmc** [comment]
@gdoyle1 @mindreeper2420 do you want me to pick this up as part of the card tweaks I was doing? Or have you already started this?

**Comment by mindreeper2420** [comment]
@alistairmc You can pick it up and include with those changes - I haven't started any of this yet.
