### ISSUE TITLE
Video hero is missing author reference

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/rhd-frontend#307]
This should use the author element reference as seen in articles.
![Screen Shot 2019-10-07 at 1 45 49 PM](https://user-images.githubusercontent.com/30870144/66335344-df7c8280-e908-11e9-8e2a-af91a61abee7.png)

Also the video title should be an H3

**Comment by jordanpagewhite** [comment]
I confirmed with Gina in Slack that this issue is now resolved in Drupal.
