### ISSUE TITLE
GET https://localhost/themes/custom/rhdp2/css/assets/fonts/RedHatText/RedHatText-Medium.woff net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/rhd-frontend#308]
We are getting this error in the JS console in Drupal:

```
GET https://localhost/themes/custom/rhdp2/css/assets/fonts/RedHatText/RedHatText-Medium.woff net::ERR_ABORTED 404 (Not Found)
```

Is this something that we need to resolve before deploying this DX Surge?

**Comment by mindreeper2420** [comment]
For some reason, the build scripts are not copying the font files from the PatternFly dependency to the distribution folder (located under `node_modules/@patternfly/patternfly/assets/fonts/`). The SCSS variable under `src/styles/rhd-theme/_pf_import.scss` also needs to be added to point to wherever the folder is copied over to.

```
// Fontpath
$pf-global--font-path: "./assets/fonts" !default;
```

This should be resolved as, without these files, the browsers will default to the next available font, usually Helvetica or Arial.
