### ISSUE TITLE
./src/scripts/@rhd/js/custom-jira-collector.js not in rhd.old.min.js

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/rhd-frontend#309]
It looks like ./src/scripts/@rhd/js/custom-jira-collector.js is not loaded into rhd.old.min.js. We need the JS in custom-jira-collector.js for the Report website issue link in the footer.

### Acceptance Criteria

- The JS in custom-jira-collector.js is available in the dist JS file(s), presumably rhd.old.min.js

**Comment by mindreeper2420** [comment]
@jordanpagewhite It looks like `custom-jira-collector.js` is rolled up into `rhd.min.js`. Is that file available?

<img width="548" alt="Screen Shot 2019-10-07 at 4 16 35 PM" src="https://user-images.githubusercontent.com/4032718/66345333-df3ab200-e91d-11e9-9b33-a536017dee50.png">

**Comment by jordanpagewhite** [comment]
I have resolved this issue https://github.com/redhat-developer/developers.redhat.com/issues/3122 and https://github.com/redhat-developer/developers.redhat.com/pull/3166. Thanks @mindreeper2420
