### ISSUE TITLE
Jump-to-nav mobile breakpoint spacing and hover text color

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/rhd-frontend#316]
<img width="478" alt="Screen Shot 2019-10-08 at 1 21 24 PM" src="https://user-images.githubusercontent.com/7155034/66430309-a9093b00-e9ce-11e9-91e4-1127330bdc68.png">

@sjcox-rh @gdoyle1 Can you give some UX advice for this component on mobile viewports? At the very least, it seems that we should change the hover bg + text color

**Comment by gdoyle1** [comment]
@jordanpagewhite We can continue having it break as it does currently https://developers.redhat.com/topics/kubernetes/ with 24px spacing between each of the items assuming that can work in the grid! And then on hover we can have it white with blue text instead (so keep the white hover you have here and turn the text to blue).
