### ISSUE TITLE
Product download hero spacing fixes

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/rhd-frontend#353]
Top padding is missing and secondary cta needs to be moved to right of main cta.

Current implementation:
<img width="1564" alt="Screen Shot 2019-10-14 at 11 25 47 PM" src="https://user-images.githubusercontent.com/16257540/66805717-8ef1c000-eeda-11e9-9de3-7737f1ef2060.png">

Correct Design:
<img width="1220" alt="Screen Shot 2019-10-14 at 11 29 06 PM" src="https://user-images.githubusercontent.com/16257540/66805756-a92b9e00-eeda-11e9-9cfb-3f3d2fa56df3.png">

Fixes to be made:
- Top and bottom margin of whole assembly to be 24px
- additional top and bottom margin on text area to be 48px
- Move secondary CTA to left of main CTA (use 24 px space between)
- version number should be 12pt

**Comment by rogeralloymagnetic** [comment]
Just to confirm that this does seem to be an issue/regression in the FE repo, not the Drupal implementation:
https://redhat-developer.github.io/rhd-frontend/components/product-download-hero/
