### ISSUE TITLE
Product download cards 404 links

### ISSUE THREAD

**Issue by alistairmc** [redhat-developer/rhd-frontend#354]
On the Products page the three product cards link to broken pages (404)

https://developers.dev.redhat.com/products/

![Screenshot 2019-10-15 at 08 54 28](https://user-images.githubusercontent.com/900631/66811900-ce93c880-ef29-11e9-894a-966462c58b03.png)

**Comment by jordanpagewhite** [comment]
This was closed by https://github.com/redhat-developer/developers.redhat.com/pull/3200
