### ISSUE TITLE
Fix Topic Nav to show "All Topics" on mobile

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/rhd-frontend#363]
On tablet and mobile, "all topics" link is either dropped to a second line, or missing altogether.

When screen sizes down to no longer fit topics link and the "All Topic" link, still include it in the horizontal scroll.

<img width="722" alt="Screen Shot 2019-10-15 at 8 51 42 AM" src="https://user-images.githubusercontent.com/16257540/66848095-50372680-ef29-11e9-9e3b-886a77d7374e.png">

Don't drop it to a second line, like below:
<img width="1021" alt="Screen Shot 2019-10-15 at 8 51 57 AM" src="https://user-images.githubusercontent.com/16257540/66848130-5decac00-ef29-11e9-834b-3ec2b73272d7.png">

**Comment by adelasofia** [comment]
This was fixed on https://github.com/redhat-developer/rhd-frontend/pull/361/
