### ISSUE TITLE
Missing gutters on all Articles

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/rhd-frontend#365]
Some regression happened that removed gutters from all articles.  All content now bleeding to edge of page.

<img width="1679" alt="Screen Shot 2019-10-15 at 9 14 34 AM" src="https://user-images.githubusercontent.com/16257540/66849724-3ba85d80-ef2c-11e9-943c-8b79e2285a3a.png">

**Comment by rogeralloymagnetic** [comment]
@sjcox-rh this is actually an issue with the Drupal implementation. I've created this ticket in developers.redhat.com: https://github.com/redhat-developer/developers.redhat.com/issues/3199 and am closing this one.
